"""empty message

Revision ID: acf1dcf2dda5
Revises: 
Create Date: 2025-03-22 09:42:45.123761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf1dcf2dda5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('dept_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('dept_id'),
    sa.UniqueConstraint('dept_name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=100), nullable=False),
    sa.Column('lname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('student',
    sa.Column('stud_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('stud_id')
    )
    op.create_table('supervisor',
    sa.Column('superv_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['department.dept_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('superv_id')
    )
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('superv_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['department.dept_id'], ),
    sa.ForeignKeyConstraint(['superv_id'], ['supervisor.superv_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('complaint',
    sa.Column('comp_id', sa.Integer(), nullable=False),
    sa.Column('comp_datefiled', sa.DateTime(), nullable=False),
    sa.Column('comp_descr', sa.String(length=500), nullable=False),
    sa.Column('comp_status', sa.String(length=100), nullable=True),
    sa.Column('comp_dept', sa.String(length=200), nullable=False),
    sa.Column('comp_anonymous', sa.Boolean(), nullable=True),
    sa.Column('comp_dateresolved', sa.DateTime(), nullable=True),
    sa.Column('comp_doc', sa.String(length=300), nullable=True),
    sa.Column('stud_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('superv_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['stud_id'], ['student.stud_id'], ),
    sa.ForeignKeyConstraint(['superv_id'], ['supervisor.superv_id'], ),
    sa.PrimaryKeyConstraint('comp_id')
    )
    op.create_table('appeal',
    sa.Column('appeal_id', sa.Integer(), nullable=False),
    sa.Column('appeal_datefiled', sa.DateTime(), nullable=False),
    sa.Column('appeal_reason', sa.String(length=500), nullable=False),
    sa.Column('appeal_status', sa.String(length=100), nullable=True),
    sa.Column('appeal_dateresolved', sa.DateTime(), nullable=True),
    sa.Column('appeal_doc', sa.String(length=300), nullable=True),
    sa.Column('comp_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('superv_id', sa.Integer(), nullable=True),
    sa.Column('stud_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['comp_id'], ['complaint.comp_id'], ),
    sa.ForeignKeyConstraint(['stud_id'], ['student.stud_id'], ),
    sa.ForeignKeyConstraint(['superv_id'], ['supervisor.superv_id'], ),
    sa.PrimaryKeyConstraint('appeal_id'),
    sa.UniqueConstraint('comp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appeal')
    op.drop_table('complaint')
    op.drop_table('admin')
    op.drop_table('supervisor')
    op.drop_table('student')
    op.drop_table('user')
    op.drop_table('department')
    # ### end Alembic commands ###
