"""updated complaint model

Revision ID: f37dbab06bef
Revises: f62e0fe1d3b4
Create Date: 2025-03-28 06:41:04.457367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37dbab06bef'
down_revision = 'f62e0fe1d3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comp_title', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_column('comp_title')

    # ### end Alembic commands ###
