"""Allow anonymous complaints by making stud_id nullable

Revision ID: f62e0fe1d3b4
Revises: fe5c1546961b
Create Date: 2025-03-22 15:48:43.971386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62e0fe1d3b4'
down_revision = 'fe5c1546961b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('stud_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('stud_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
